model:
  type: diffusion # dsm and diffusion
  network: dualenc
  hidden_dim: 128
  num_convs_local: 2
  num_edm_block: 2
  cutoff: 3.0
  mlp_act: relu
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  # beta_schedule: linear
  # beta_start: 0.0001
  # beta_end: 0.02
  num_diffusion_timesteps: 5000
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: false
  laplacian_eigenvector: 3
  fragment_edge_type: 4
  pe_type: laplacian
  regular_data: False
  node_mask: 0.0

train:
  seed: 2021
  batch_size: 64
  val_freq: 100000
  # max_iters: 3000000
  # max_iters: 1000000
  max_iters: 200000
  # max_grad_norm: 30000.0
  max_grad_norm: 10000.0
  anneal_power: 2.0
  optimizer:
    type: adam_w
    lr: 1.e-3
    weight_decay: 0.01
    # type: adam
    # lr: 1.e-3
    # weight_decay: 0.
    # beta1: 0.95
    # beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10

dataset:
  regular: ./data/regular_graph/regular_graph.pkl
  # train: ./data/rome/train_spring_layout.pkl
  # val: ./data/rome/val_spring_layout.pkl
  # test: ./data/rome/test_spring_layout.pkl
  
  train: ./data/rome_kamada/train_layout.pkl
  val: ./data/rome_kamada/val_layout.pkl
  test: ./data/rome_kamada/test_layout.pkl

  train_circular: ./data/rome_circular/train_layout.pkl
  val_circular: ./data/rome_circular/val_layout.pkl
  test_circular: ./data/rome_circular/test_layout.pkl

  train_path: ./data/path_graph/path_graph.pkl

  train_tree: ./data/tree_graph/tree_graph.pkl

  demo_tree: ./data/tree_graph/demo_tree_graph.pkl

  demo_1_tree: ./data/tree_graph/demo_1_tree_graph.pkl

  rome_tree_path_graph: ./data/rome_tree_path_graph/rome_tree_path_graph.pkl

  final_rome: ./final_data/rome/train_layout.pkl
  final_rome_val: ./final_data/rome/val_layout.pkl

  final_hierarchy_tree: ./final_data/hierarchy_tree/train_layout.pkl
  final_hierarchy_tree_val: ./final_data/hierarchy_tree/train_layout.pkl

  final_spiral_path: ./final_data/spiral_path/train_layout.pkl
  final_spiral_path_val: ./final_data/spiral_path/train_layout.pkl

  final_circle: ./final_data/circle/train_layout.pkl
  final_circle_val: ./final_data/circle/train_layout.pkl

  final_grid: ./final_data/grid/train_layout.pkl
  final_grid_val: ./final_data/grid/train_layout.pkl

  final_triangular: ./final_data/triangular/train_layout.pkl
  final_triangular_val: ./final_data/triangular/train_layout.pkl

  final_compose: ./final_data/compose/train_layout.pkl
  final_compose_val: ./final_data/rome/val_layout.pkl

  final_compose_no_rome: ./final_data/compose_no_rome/train_layout.pkl
  final_compose_no_rome_val: ./final_data/hierarchy_tree/train_layout.pkl

  final_control_compose_no_rome: ./final_data/compose_no_rome/control_train_layout.pkl
  final_control_compose_no_rome_val: ./final_data/hierarchy_tree/control_train_layout.pkl

  # final_train: ./final_data/compose_no_rome/1_control_train_layout.pkl
  # final_val: ./final_data/hierarchy_tree/1_control_train_layout.pkl

  final_train: ./final_data/rome/train_layout.pkl
  final_val: ./final_data/rome/val_layout.pkl

  # train: ./data/rome_kamada/50_train_layout.pkl
  # val: ./data/rome_kamada/50_val_layout.pkl
  # test: ./data/rome_kamada/50_test_layout.pkl

  # train: ./data/rome_kamada/node_20_train_layout.pkl?\
  # train: ./data/rome_kamada/node_20_val_layout.pkl
  # val: ./data/rome_kamada/node_20_val_layout.pkl
  # test: ./data/rome_kamada/node_20_test_layout.pkl
  
  # train: ./data/rome/same_graph_node_50.pkl
  # val: ./data/rome/same_graph_node_50.pkl
  # test: ./data/rome/same_graph_node_50.pkl
